2025-04-14 05:00:39,381 INFO    MainThread:103084 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /workspace/notebooks/Carlos/fine_tunig_project/thesis/Step_8/wandb/run-20250414_050039-5oca2kgi/logs/debug.log
2025-04-14 05:00:39,381 INFO    MainThread:103084 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /workspace/notebooks/Carlos/fine_tunig_project/thesis/Step_8/wandb/run-20250414_050039-5oca2kgi/logs/debug-internal.log
2025-04-14 05:00:39,381 INFO    MainThread:103084 [wandb_init.py:monkeypatch_ipython():581] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f0f86bdff40>
2025-04-14 05:00:39,381 INFO    MainThread:103084 [wandb_init.py:init():781] calling init triggers
2025-04-14 05:00:39,383 INFO    MainThread:103084 [wandb_init.py:init():809] starting backend
2025-04-14 05:00:39,383 INFO    MainThread:103084 [wandb_init.py:init():813] sending inform_init request
2025-04-14 05:00:39,385 INFO    MainThread:103084 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-14 05:00:39,385 INFO    MainThread:103084 [wandb_init.py:init():823] backend started and connected
2025-04-14 05:00:39,390 INFO    MainThread:103084 [wandb_run.py:_label_probe_notebook():1267] probe notebook
2025-04-14 05:00:39,390 INFO    MainThread:103084 [wandb_run.py:_label_probe_notebook():1277] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-14 05:00:39,390 INFO    MainThread:103084 [wandb_init.py:init():915] updated telemetry
2025-04-14 05:00:39,522 INFO    MainThread:103084 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-14 05:00:39,910 INFO    MainThread:103084 [wandb_init.py:init():1014] starting run threads in backend
2025-04-14 05:00:40,095 INFO    MainThread:103084 [wandb_run.py:_console_start():2454] atexit reg
2025-04-14 05:00:40,096 INFO    MainThread:103084 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-14 05:00:40,096 INFO    MainThread:103084 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-14 05:00:40,096 INFO    MainThread:103084 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-14 05:00:40,098 INFO    MainThread:103084 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-14 05:05:06,538 INFO    MainThread:103084 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-14 05:05:06,538 INFO    MainThread:103084 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-14 05:05:39,108 INFO    MsgRouterThr:103084 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 3 handles.
2025-04-14 05:05:40,515 ERROR   Thread-1  :103084 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/workspace/notebooks/Carlos/fine_tunig_project/mi_entorno/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
